### PR TITLE
Print mode

### LINKED ISSUE #2: Change output to use standardized logging format
If the output gets piped into a log aggregator it should have timestamps and delimiters and all that.

### PR DESCRIPTION
**Pull request by begriffs**
A reimplementation of https://github.com/begriffs/pg_listen/pull/8 with ideas from @andytango

Fixes #2 

Closes #8

### CODE REVIEW

**Comment by begriffs** [comment]
@steve-chavez and @andytango can you guys do a code review on this PR please and try out the feature?

**Comment by steve-chavez** [comment]
Not sure what I'm doing wrong, but printing to stdout is not working for me:
```bash
## invoking it as usual
./pg_listen postgres://localhost/postgres fun /run/current-system/sw/bin/cat
2020-02-11T17:47:35 - pg_listen - INFO - Listening on channel "fun"
## notify fun, 'test1';
## notify fun, 'test2';
test1test2

## No program
./pg_listen postgres://localhost/postgres fun
2020-02-11T17:50:29 - pg_listen - INFO - Listening on channel "fun"
## notify fun, 'test1';
## notify fun, 'test2';
## No output

## With pipe
./pg_listen postgres://localhost/postgres fun | cat
2020-02-11T17:52:18 - pg_listen - INFO - Listening on channel "fun"
## notify fun, 'test1';
## notify fun, 'test2';
## No output
```

**Comment by begriffs** [comment]
Ah, that's a tricky part. In print mode pg_listen enables line buffering on stdout, so the buffer doesn't get flushed until it encounters a newline. You should see output with this:

```sql
notify fun, E'test1\n';
```

I was thinking of having pg_listen add a newline to the payload, but then a payload that already had one would cause a blank line to be printed. Alternately pg_listen could add the newline only if it didn't already exist, or could use another buffering setting.

**Comment by steve-chavez** [comment]
Oh I see, now it works. I'm out of my depth here but why not have the stream unbuffered? Just changed `setvbuf` to use `_IONBF` and it worked without the newline.

**Comment by andytango** [comment]
Hi guys sorry for the delay on my side. 

Websocketd uses newlines to delimit each message it sends but I'm wrapping my `NOTIFY` statements in a plpgsql function anyway (like most users presumably would?), so it isn't to difficult to format in the newline as in @begriffs 's example. 

If you did append the newline when already provided that would seem the idiomatic way to me.

Apart from that all works fine and I can't see any issues with the source code.

**Comment by begriffs** [comment]
Steve Chavez wrote:
> why not have the > stream unbuffered?

I believe that if it's unbuffered it has to make a system call for every
character sent to the stream, which is less efficient than batching the
characters into a bigger buffer for the call.

I guess we have to balance that with the confusion it may cause if
people notify with non-newline delimited payloads. I can add that caveat
to the README and then wait and see if we get any issues filed.

**Comment by begriffs** [comment]
Andrew Hall wrote:
> If you did append the newline when already provided that would seem
> the idiomatic way to me.

I probably wouldn't want to add a newline and cause a string to end in
"\n\n" or else there would be a blank link in the output. Piping that to
a line-oriented program might cause it to try to process empty lines.

> Apart from that all works fine and I can't see any issues with the
> source code.

I'll merge it then, and we can fix it later if it causes problems.

**Pull request merged**
