### PR TITLE
Stdout option

### PR DESCRIPTION
**Pull request by andytango**
Allow users to supply `-` as the script argument, sending the notification payload to stdout instead of a forked process.

- Altered all existing log messages to print to stderr
- Replaced `listen_forever` with two strategies, `exec` and `print`.
- Extracted function for reuse across these, `listen_poll`

### CODE REVIEW

**Comment by begriffs** [comment]
Thanks for the pull request!

> - Altered all existing log messages to print to stderr

That makes a lot of sense. It'll avoid mixing the logging output with
real program output from commands it spawns.

> Allow users to supply `-` as the script argument, sending the
> notification payload to stdout instead of a forked process.

Can you explain the motivation for this change? I believe the
functionality is already possible like this:

	pg_listen postgres://foo bar /bin/cat -

Doing it this way avoids duplicate logic inside pg_listen.

**Comment by begriffs** [comment]
Joe Nelson wrote:
> That makes a lot of sense. It'll avoid mixing the logging output with
> real program output from commands it spawns.

While you're at it, standardizing the log format would be great too.
Each line should be of the form

	date time - pg_listen - {DEBUG,INFO,WARNING,ERROR,CRITICAL} - message

That would take care of https://github.com/begriffs/pg_listen/issues/2

**Comment by andytango** [comment]
> Thanks for the pull request!

No problem!

> Can you explain the motivation for this change? I believe the functionality is already possible like this: `pg_listen postgres://foo bar /bin/cat - Doing it this way avoids duplicate logic inside pg_listen

Two reasons:

1. I was planning to use pg_listen with this tool [websocketd](http://websocketd.com/), which runs a supplied program whenever a client connects to its websocket server, and passes that program's stdin/stdout to the websocket channel.

So instead of:
`pg_listen postgres://foo bar /bin/cat `,

I wanted to do something like:
`websocketd --port=8080 pg_listen -`, which would invoke pg_listen each time a client connects to the websocket channel, and send any postgres notifications to the websocket client.

I could be missing something though - do you think there might be a better way to handle this?

2. It seemed to me that bringing in another process, `cat`, and running the logic to fork and manage it, is (a tiny bit) wasteful from the system resources perspective, and less user-friendly than the hyphen `-` option?

I'll add in the log messages later today 🙂

**Comment by begriffs** [comment]
It's true that executing another binary and piping data to it is less efficient than simply printing output ourselves. However it's probably not too big of a deal, and I'd rather not complicate internal logic for something that a composition of UNIX tools can do for us, at least until we see that there's a compelling performance reason to do so.

Also the convention with "-" is a GNUism, not POSIX compliant so I don't want to promulgate it in this utility. (You were right to remove it from cat in my example.)

Can you try `websocketd --port=8080 pg_listen postgres://foo bar /bin/cat` to see whether it works?

Also for the logging, bringing in that other library feels kind of heavy, given we don't need colors and thread safety. That logging code practically doubles the code in this project. What about using a simple function like this:

```c
int print_log(const char *sev, const char *msg)
{
	time_t now = time(NULL);
	char timestamp[128];

	strftime(timestamp, sizeof timestamp,
		"%d/%b/%Y:%H:%M:%S %z", gmtime(&now));
	return fprintf(stderr,
		"%s - pg_listen - %s - %s\n",
		timestamp, sev, msg);
}
```

(Adjusting the timestamp format as you see fit)

**Comment by begriffs** [comment]
Come to think of it, we'll probably need it to be

```c
int print_log(const char *sev, const char *msg, ...)
```

and use vfprintf inside because some of our error messages themselves have %s inside. It'll be a little more complicated than my code snippet, but I don't think much worse.

**Comment by andytango** [comment]
Have pushed logging changes as requested and appears to all work ok.

> Can you try websocketd --port=8080 pg_listen postgres://foo bar /bin/cat to see whether it works?

So I tried this with my implementation (printing to stdout without using cat), and found that I had to disable stdout buffering as postgres NOTIFY payloads tend (and ought) to be quite small.

When using it websocketd _with_ `cat`, I failed to get any websocket messages out. I wondered if the process `cat` itself had the same buffering issue as above, so I pushed through a large volume of NOTIFYs that would cause stdout to flush, but still had no luck. 

At present I'm really not sure why it isn't working but will continue to investigate with my colleagues.

> It's true that executing another binary and piping data to it is less efficient than simply printing output ourselves. However it's probably not too big of a deal, and I'd rather not complicate internal logic for something that a composition of UNIX tools can do for us, at least until we see that there's a compelling performance reason to do so.

Yep I can see that the performance difference is slight, and that simplicity is a clear goal for this project. I suppose it's a matter of how you prioritise different kinds of simplicity, be it run-time overhead, user interface or internal logic. Perhaps there's a way to simplify the internal logic? C really isn't my primary language, as you can probably tell...

It was actually the idea of UNIX composition drew me to both this project and websocketd for what I'm trying to achieve. Namely, a microservice with minimal dependencies and maintenance overhead.  
Couldn't it be argued that providing an easier means for users to compose this tool is working towards, rather than against, the UNIX philosophy? I'm specifically thinking of: "Write programs that do one thing and do it well. Write programs to work together. Write programs to handle text streams, because that is a universal interface."

> Also the convention with "-" is a GNUism, not POSIX compliant so I don't want to promulgate it in this utility. (You were right to remove it from cat in my example.)

As it happens I wasn't aware of that, I may have missed the "-" when pasting your quote! Very interesting. If that's the case, we could make the 'script' argument optional? If no script is provided, we default to stdout?

**Comment by andytango** [comment]
@begriffs Are you still interested in this PR?

**Comment by steve-chavez** [comment]
It's a bit cumbersome to specify the path sometimes. For example in distros like NixOS I would use: `pg_listen db-uri channel /run/current-system/sw/bin/curl`. The stdout option would be convenient for avoiding that. Not something critical for me, but would be nice.

**Comment by begriffs** [comment]
> It's a bit cumbersome to specify the path sometimes.

I see what you mean. I have a patch I'm working on based on this PR and
I'll share it when it's done. May be a few more days though given some
other things I'm working on.

**Pull request closed without merging**
